// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWOt5ecG9xFe9NugIFZi2FuWOQDgTOWl0',
    appId: '1:278024505043:web:fa85d2d8502f7450117626',
    messagingSenderId: '278024505043',
    projectId: 'fakevisionfyp',
    authDomain: 'fakevisionfyp.firebaseapp.com',
    storageBucket: 'fakevisionfyp.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBaueYSLuzWiBXTRf3xC_fjui7esR-X-5M',
    appId: '1:278024505043:android:8db4e7bece565d17117626',
    messagingSenderId: '278024505043',
    projectId: 'fakevisionfyp',
    storageBucket: 'fakevisionfyp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDliw4qoU6CpXT7CneTsrF8AB_UoNCtgTM',
    appId: '1:278024505043:ios:c37223b1dc706ac9117626',
    messagingSenderId: '278024505043',
    projectId: 'fakevisionfyp',
    storageBucket: 'fakevisionfyp.appspot.com',
    iosBundleId: 'com.example.fakeVision',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDliw4qoU6CpXT7CneTsrF8AB_UoNCtgTM',
    appId: '1:278024505043:ios:f28d732e871ab0cc117626',
    messagingSenderId: '278024505043',
    projectId: 'fakevisionfyp',
    storageBucket: 'fakevisionfyp.appspot.com',
    iosBundleId: 'com.example.fakeVision.RunnerTests',
  );
}
